google/DirectXShaderCompiler

CMakeLists.txt
appveyor.yml
cmake/modules/AddLLVM.cmake
tools/clang/lib/CMakeLists.txt
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/tools/dxc/dxc.cpp
tools/clang/tools/dxcompiler/CMakeLists.txt
tools/clang/tools/dxcompiler/dxcompilerobj.cpp
tools/clang/unittests/CMakeLists.txt
tools/clang/unittests/SPIRV/ModuleBuilderTest.cpp
utils/hct/hctbuild.cmd

* Add a new SPIRV_BUILD_TESTS option to control building of
SPIR-V tests. The original ENABLE_SPIRV_CODEGEN is only used
for turning on SPIR-V codegen in the library right now.
* SPIRV_BUILD_TESTS turns on ENABLE_SPIRV_CODEGEN implicitly.
* Add a new -spirvtest option to hctbuild to build SPIR-V tests.

Use two options to control SPIR-V build and test and update generator number

---

tools/clang/include/clang/SPIRV/Decoration.h
tools/clang/include/clang/SPIRV/SPIRVContext.h
tools/clang/include/clang/SPIRV/Type.h
tools/clang/include/clang/SPIRV/Utils.h
tools/clang/lib/SPIRV/CMakeLists.txt
tools/clang/lib/SPIRV/Decoration.cpp
tools/clang/lib/SPIRV/InstBuilderManual.cpp
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/lib/SPIRV/SPIRVContext.cpp
tools/clang/lib/SPIRV/Type.cpp
tools/clang/lib/SPIRV/Utils.cpp
tools/clang/unittests/SPIRV/CMakeLists.txt
tools/clang/unittests/SPIRV/DecorationTest.cpp
tools/clang/unittests/SPIRV/SPIRVContextTest.cpp
tools/clang/unittests/SPIRV/TypeTest.cpp
tools/clang/unittests/SPIRV/UtilsTest.cpp

* Added support for decorations and types.
* Introduced clang::spirv::utils
* Avoid static members in Type and Decoration based on design doc
comments. Types and Decorations are unique in the context in which
they are defined. Therefore, each context should track its own types, etc.
* getTypeXXX and getDecorationXXX functions should take a context
argument (similar to LLVM).
* Added a number of unit tests (TODO: more unit tests).

Added Decoration, Type, and utils.

---

tools/clang/include/clang/SPIRV/Type.h
tools/clang/include/clang/SPIRV/Utils.h
tools/clang/lib/SPIRV/Type.cpp
tools/clang/lib/SPIRV/Utils.cpp
tools/clang/unittests/SPIRV/SPIRVContextTest.cpp
tools/clang/unittests/SPIRV/TypeTest.cpp
utils/hct/hctbuild.cmd

Also made a change to the Type class as follows:
a) Type::getType function has been removed in order to prevent users from
constructing invalid types.
b) All Type::get...() functions have been updated to accept decorations
as argument in order to allow building any valid arbitrary type.

Adding Type Unit Tests.

---

tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/unittests/SPIRV/WholeFileCheck.cpp

* Added DiagnosticsEngine to the SPIRVEmitter
* Updated the WholeFileCheck flow to show the warning and error
messages.
* If an Error level message is added to the Diagnostics, the compiler is
considered to have failed (gtest will be marked as FAILED).
* Warning level messages are printed and considered a PASS.

[spirv] Start using DiagnosticsEngine.

---

tools/clang/include/clang/SPIRV/BlockReadableOrder.h
tools/clang/include/clang/SPIRV/Constant.h
tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/include/clang/SPIRV/Structure.h
tools/clang/lib/SPIRV/BlockReadableOrder.cpp
tools/clang/lib/SPIRV/CMakeLists.txt
tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/lib/SPIRV/Structure.cpp
tools/clang/test/CodeGenSPIRV/cf.if.for.hlsl
tools/clang/test/CodeGenSPIRV/for-stmt.nested.hlsl
tools/clang/test/CodeGenSPIRV/if-stmt.nested.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
tools/clang/unittests/SPIRV/ConstantTest.cpp
tools/clang/unittests/SPIRV/SPIRVContextTest.cpp

SPIR-V spec requires basic blocks to appear in an order satisfying
the dominator-tree direction. Added a BlockReadableOrderVisitor
class for visiting basic blocks in a human-readable order following
the spec's requirements.
Also fixed a bug in `Constant::operator==()`, which causes hashing
weirdness.

[spirv] Handle basic block orders

---

docs/SPIR-V.rst
tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/test/CodeGenSPIRV/intrinsics.dot.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

The translation supports dot product of vectors of floats using SPIR-V's
OpDot.
The translation also supports dot product of vectros of integers using
multiplication and addition.

[spirv] Translate intrinsic dot product.

---

external/CMakeLists.txt

With this change, targets in the subdirectory will not be included
in the ALL target of the parent directory by default, and will be
excluded from IDE project files.

[spirv] Use EXCLUDE_FROM_ALL to ignore unused external targets

---

tools/clang/lib/SPIRV/CMakeLists.txt
tools/clang/lib/SPIRV/InitListHandler.cpp
tools/clang/lib/SPIRV/InitListHandler.h
tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.h
tools/clang/lib/SPIRV/TypeTranslator.cpp
tools/clang/lib/SPIRV/TypeTranslator.h
tools/clang/test/CodeGenSPIRV/var.init.hlsl
tools/clang/test/CodeGenSPIRV/var.init.matrix.1x1.hlsl
tools/clang/test/CodeGenSPIRV/var.init.matrix.1xn.hlsl
tools/clang/test/CodeGenSPIRV/var.init.matrix.mx1.hlsl
tools/clang/test/CodeGenSPIRV/var.init.matrix.mxn.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

Initializer lists are flexible in HLSL to the extent that as long
as the total number elements is correct, it will be accepted.
To support such flexibility, we need to conduct composite
extraction/construction and proper casting when necessary.
A new dedicated class is introduced for handling initializer lists.
It is built on top of the SPIRVEmitter class. It holds the logic
for correct initializer list handling and calls into SPIRVEmitter
for normal translating tasks. So is in a sense higher level than
the SPIRVEmitter class.
Also extended cast methods and vector type probing functions to
support ExtVectorType since we need to construct ExtVectorType
when handling intializer lists.

[spirv] Revise to provide more initializer list support

---

tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
tools/clang/lib/SPIRV/DeclResultIdMapper.h
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/test/CodeGenSPIRV/spirv.storage-class.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

We now compute and store decl storage class in DeclResultIdMapper.
Querying is done using RecursiveASTVisitor to check DeclRefExpr,
FunctionDecl, ParmVarDecl, and FieldDecl for normal and remapped
Decls.
Fixed various hard coded storage class in SPIRVEmitter.

[spirv] Derive storage class properly from original variables

---

tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/TypeTranslator.cpp
tools/clang/lib/SPIRV/TypeTranslator.h

Make the type probing methods in TypeTranslator much more clear
as for their responsibilities.

[spirv] Sanitize scalar/vector/matrix type probing methods

---

docs/SPIR-V.rst
tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
tools/clang/lib/SPIRV/DeclResultIdMapper.h
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.h
tools/clang/test/CodeGenSPIRV/break-stmt.mixed.hlsl
tools/clang/test/CodeGenSPIRV/cf.if.for.hlsl
tools/clang/test/CodeGenSPIRV/constant-ps.hlsl2spv
tools/clang/test/CodeGenSPIRV/empty-void-main.hlsl2spv
tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv
tools/clang/test/CodeGenSPIRV/passthru-vs.hlsl2spv
tools/clang/test/CodeGenSPIRV/semantic.arbitrary.hlsl
tools/clang/test/CodeGenSPIRV/semantic.depth.ps.hlsl
tools/clang/test/CodeGenSPIRV/semantic.instance-id.ps.hlsl
tools/clang/test/CodeGenSPIRV/semantic.instance-id.vs.hlsl
tools/clang/test/CodeGenSPIRV/semantic.position.ps.hlsl
tools/clang/test/CodeGenSPIRV/semantic.position.vs.hlsl
tools/clang/test/CodeGenSPIRV/semantic.target.ps.hlsl
tools/clang/test/CodeGenSPIRV/semantic.vertex-id.vs.hlsl
tools/clang/test/CodeGenSPIRV/spirv.entry-function.wrapper.hlsl
tools/clang/test/CodeGenSPIRV/spirv.storage-class.hlsl
tools/clang/test/CodeGenSPIRV/var.init.hlsl
tools/clang/test/CodeGenSPIRV/var.init.struct.hlsl
tools/clang/test/CodeGenSPIRV/var.static.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

Previously for an entry function, we decompose its parameters and
return value and create stage input/output/builtin variables from
them directly. This is fine for simple shaders, but it will have
problems for shaders using structs to group stage variables.
Accessing paramters and return values (using operator. and return)
needs special handling for entry functions, which is nasty.
With the wrapper function, we can handle entry functions just like
normal functions. Stage variable handling are all done in the
wrapper funtion.

[spirv] Converted to generate wrapper for entry function

---

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
tools/clang/lib/SPIRV/DeclResultIdMapper.h
tools/clang/test/CodeGenSPIRV/constant-ps.hlsl2spv
tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv
tools/clang/test/CodeGenSPIRV/passthru-vs.hlsl2spv
tools/clang/test/CodeGenSPIRV/semantic.arbitrary.location.hlsl
tools/clang/test/CodeGenSPIRV/semantic.duplication.hlsl
tools/clang/test/CodeGenSPIRV/semantic.target.ps.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
tools/clang/unittests/SPIRV/FileTestFixture.cpp
tools/clang/unittests/SPIRV/FileTestFixture.h
tools/clang/unittests/SPIRV/FileTestUtils.cpp
tools/clang/unittests/SPIRV/FileTestUtils.h
tools/clang/unittests/SPIRV/WholeFileTestFixture.cpp

SV_Target[N] is treated differently; they will always be assigned
the location N. For other semantics that does not map to builtin
variables, assign locations to them alphabetically.

[spirv] Assign locations to stage I/O variables alphabetically

---

tools/clang/include/clang/Basic/Attr.td
tools/clang/include/clang/Basic/LangOptions.h
tools/clang/include/clang/Parse/Parser.h
tools/clang/lib/Parse/ParseDeclCXX.cpp
tools/clang/lib/Parse/ParseTentative.cpp
tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
tools/clang/lib/SPIRV/DeclResultIdMapper.h
tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/Sema/SemaHLSL.cpp
tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv
tools/clang/test/CodeGenSPIRV/vk.location.exp-in.hlsl
tools/clang/test/CodeGenSPIRV/vk.location.exp-out.hlsl
tools/clang/test/CodeGenSPIRV/vk.location.hlsl
tools/clang/test/CodeGenSPIRV/vk.location.large.hlsl
tools/clang/test/CodeGenSPIRV/vk.location.mixed.hlsl
tools/clang/test/CodeGenSPIRV/vk.location.reassign.hlsl
tools/clang/test/HLSL/cxx11-attributes.hlsl
tools/clang/tools/dxcompiler/dxcompilerobj.cpp
tools/clang/unittests/HLSL/VerifierTest.cpp
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
tools/clang/utils/TableGen/ClangAttrEmitter.cpp

This commit turns on C++11 attributes for HLSL globally. C++11
attributes will be parsed where they are allowed in C++11.
However, they will just result in an warning of ignored attribute,
without any semantic impact for the general DXIL codegen.
For SPIR-V codegen, C++11 attributes within the vk namespace will
be interpreted and converted to semantic AST nodes.

[spirv] Turn on C++11 attributes and support [[vk::location(X)]]

---

tools/clang/tools/CMakeLists.txt
tools/clang/tools/hlsl2spirv/CMakeLists.txt
tools/clang/tools/hlsl2spirv/hlsl2spirv.cpp

`hlsl2spirv.exe -T <profile> -E <entry> <input file.hlsl>` will
translate HLSL to SPIR-V and output the results on the terminal.
Alternatively, `-Fc <assembly output file name>`  can be used to write
the resulting SPIR-V assembly into a file.
As always, `-Fo <binary output file name>` will write the binary output
to the specified file.
The `-Fc` and `-Fo` may also be used simultaneously to get both the
binary and the assembly.

[spirv] First version of hlsl2spirv.exe.

---

docs/SPIR-V.rst
tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
tools/clang/lib/SPIRV/DeclResultIdMapper.h
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/TypeTranslator.cpp
tools/clang/lib/SPIRV/TypeTranslator.h
tools/clang/test/CodeGenSPIRV/type.sampler.hlsl
tools/clang/test/CodeGenSPIRV/type.texture.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

This commit add support for the following types:
* Texture1D, Texture2D, Texture3D, TextureCube
* Texture1DArray, Texture2DArray, TextureCubeArray
* SamplerState, SamplerComparisonState, sampler
Buffer, Texture2DMS, and Texture2DMSArray is not supported yet,
also setting sampler states.
Texture types will be translated OpTypeImage, and sampler types
will be translated into OpTypeSampler.

[spirv] Support texture and sampler types

---

tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.h
tools/clang/test/CodeGenSPIRV/texture.array.gather.hlsl
tools/clang/test/CodeGenSPIRV/texture.array.load.hlsl
tools/clang/test/CodeGenSPIRV/texture.array.sample-bias.hlsl
tools/clang/test/CodeGenSPIRV/texture.array.sample-grad.hlsl
tools/clang/test/CodeGenSPIRV/texture.array.sample-level.hlsl
tools/clang/test/CodeGenSPIRV/texture.array.sample.hlsl
tools/clang/test/CodeGenSPIRV/texture.gather.hlsl
tools/clang/test/CodeGenSPIRV/texture.load.hlsl
tools/clang/test/CodeGenSPIRV/texture.sample-bias.hlsl
tools/clang/test/CodeGenSPIRV/texture.sample-grad.hlsl
tools/clang/test/CodeGenSPIRV/texture.sample-level.hlsl
tools/clang/test/CodeGenSPIRV/texture.sample.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

This commit add support for the following methods on textures:
* .Sample()
* .SampleLevel()
* .SampleGrad()
* .SampleBias()
* .Load()
* .Gather()

[spirv] Support six texture methods

---

tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/include/clang/SPIRV/Structure.h
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.h
tools/clang/test/CodeGenSPIRV/texture.array.gather.hlsl
tools/clang/test/CodeGenSPIRV/texture.array.sample-bias.hlsl
tools/clang/test/CodeGenSPIRV/texture.array.sample-grad.hlsl
tools/clang/test/CodeGenSPIRV/texture.array.sample-level.hlsl
tools/clang/test/CodeGenSPIRV/texture.load.hlsl
tools/clang/test/CodeGenSPIRV/texture.sample-bias.hlsl
tools/clang/test/CodeGenSPIRV/texture.sample-grad.hlsl
tools/clang/test/CodeGenSPIRV/texture.sample-level.hlsl
tools/clang/test/CodeGenSPIRV/texture.sample.hlsl

Non-constant offset should be translated into the Offset image
operands instead of ConstOffset.

[spirv] Support non-constant offset in texture methods

---

docs/SPIR-V.rst
tools/clang/include/clang/Basic/Attr.td
tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
tools/clang/lib/SPIRV/DeclResultIdMapper.h
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/Sema/SemaHLSL.cpp
tools/clang/test/CodeGenSPIRV/vk.binding.explicit.error.hlsl
tools/clang/test/CodeGenSPIRV/vk.binding.explicit.hlsl
tools/clang/test/CodeGenSPIRV/vk.binding.implicit.hlsl
tools/clang/test/CodeGenSPIRV/vk.binding.register.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

This commit add support for resource binding number assignment via
both the explicit and the implicit way.
The explicit way:
[[vk::binding(X[, Y])]] is introduced, with X denoting the binding
number and the optional Y denoting the set number. If Y is missing,
the set number will be set to 0. This attribute can only be attached
to variables.
The implicit way:
register(xX, spaceY) will be used to deduce the correct set and
binding number for a given resource. X will be used as the binding
number and Y will be used as the set number. Right now we do not
consider the resource type x, which means binding numbers can
overlap given the same X and Y but not x. That is to be addressed
later.

[spirv] Support setting resource binding numbers

---

docs/SPIR-V.rst
include/dxc/Support/HLSLOptions.h
include/dxc/Support/HLSLOptions.td
lib/DxcSupport/HLSLOptions.cpp
tools/clang/include/clang/SPIRV/EmitSPIRVAction.h
tools/clang/include/clang/SPIRV/EmitSPIRVOptions.h
tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
tools/clang/lib/SPIRV/DeclResultIdMapper.h
tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.h
tools/clang/test/CodeGenSPIRV/passthru-vs.hlsl2spv
tools/clang/test/CodeGenSPIRV/semantic.arbitrary.location.alpha.hlsl
tools/clang/test/CodeGenSPIRV/semantic.arbitrary.location.decl.hlsl
tools/clang/test/CodeGenSPIRV/vk.location.exp-in.hlsl
tools/clang/test/CodeGenSPIRV/vk.location.exp-out.hlsl
tools/clang/tools/dxc/dxc.cpp
tools/clang/tools/dxcompiler/dxcompilerobj.cpp
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
tools/clang/unittests/SPIRV/FileTestFixture.cpp
tools/clang/unittests/SPIRV/FileTestFixture.h
tools/clang/unittests/SPIRV/FileTestUtils.cpp
tools/clang/unittests/SPIRV/FileTestUtils.h
tools/clang/unittests/SPIRV/WholeFileTestFixture.cpp
tools/clang/unittests/SPIRV/WholeFileTestFixture.h

A new CL option -fvk-stage-io-order={alpha|decl} is added to
control the order for assigning stage I/O location numbers.
The default is also changed to declaration order (decl) instead
of alphabetical order (alpha).
Also extended testing fixtures to support additional CL options.

[spirv] Add CL option for stage I/O location assignment order

---

lib/HLSL/DxilValidation.cpp

Using an enum class as the key of an unordered_set is supported starting
C++14.
The two possible solutions are: a) provide a hash function b) cast to
unsigned. Given the usage here, it latter is a simpler fix.

[linux-port] Avoid using enum class as set key.

---

.travis.yml
appveyor.yml

Expecting Appveyor to pass (it is currently only running Linux build).
Expecting Travis clang jobs to pass and gcc jobs to fail.

[linux-port] Enable Travis and Appveyor

---

include/dxc/Support/dxcapi.use.h
include/llvm/Support/WinMacros.h
include/llvm/Support/WinTypes.h
lib/DxcSupport/FileIOHelper.cpp
lib/DxcSupport/dxcapi.use.cpp
tools/clang/lib/Sema/SemaHLSL.cpp
tools/clang/tools/dxc/dxc.cpp
tools/clang/tools/libclang/dxcrewriteunused.cpp

Add a non-windows implementation of CW2AEX and CA2WEX using std::
character conversion functions to WinTypes.h header. Includes
CW2A and CW2A macros the same way Windows does
fix https://github.com/google/DirectXShaderCompiler/issues/172

[linux-port] Implement CA2W/CW2A conversion (#172)

---

include/llvm/IR/DiagnosticPrinter.h
include/llvm/Support/raw_ostream.h
lib/HLSL/DxilRootSignature.cpp
lib/IR/DiagnosticPrinter.cpp
lib/Support/raw_ostream.cpp

DiagnosticPrinter doesn't support io manipulators like std::hex,
in spite of that, including them in the output stream with MSVC
succeeded because it interpretted std::hex as a void pointer, which
is supported.
This adds support of it by adding an overloaded operator<< that takes
the type of std::hex and its friends and sets a base number which is
used when the base is not 10 to print numbers in the specified base,
which can only be 8 or 16 according to what is passed in.
Fixes https://github.com/google/DirectXShaderCompiler/issues/170

[linux-port] Fix DiagnosticPrinter use of std::hex

---

CMakeLists.txt

This should fix the Travis failures we are seeing.

Fix cmake for non-appveyor buildbot environments.

---

include/dxc/HLSL/DxilConstants.h
include/dxc/Support/Global.h
tools/clang/include/clang/AST/HlslTypes.h
tools/clang/include/clang/AST/Type.h
tools/clang/lib/CodeGen/CGHLSLMS.cpp

Just a few warning conditions in a handful of common headers
was producing pages and pages of warning messages. By fixing them,
the output spew is reduced significantly.
Static variables in a header produce a separate variable for every
file that includes it. In many of these, these variables were unused.
Instead, variables used in multiple files should be defined only
once in a source file and declared as extern in the header.
The implementation of DXASSERT for non-MS platforms in Global.h
included a character array as part of the assert conditional
which is always true, producing a warning. Furthermore, I don't
think this would do what was expected as it would present no
string. Instead, the message is printed out and an assert is raised.
Many unsigned variables were checked to be …

[linux-port] Fix a handful of warnings in headers

---

.travis.yml
cmake/modules/HandleLLVMOptions.cmake
lib/HLSL/DxilDebugInstrumentation.cpp
lib/HLSL/DxilOperations.cpp
lib/HLSL/DxilShaderModel.cpp
lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp

GCC5 has a few limitations that later versions do not. The
most pervasive issue is the confusion of scoped operators on enum
names when the name of the enum is shared with a local variable.
The only other issue concerns intialization of a union containing
structs and how many curly braces is enough.
Added the --std=c++11 flag because it is not enabled by default in
GCC prior to 6 and 6 doesn't mind if you specify it redundantly.
Addresses https://github.com/google/DirectXShaderCompiler/issues/196

[linux-port] Allow GCC5 compiling

---

include/llvm/Support/WinMacros.h
include/llvm/Support/WinTypes.h
lib/DxcSupport/FileIOHelper.cpp
lib/DxcSupport/dxcmem.cpp

The previous macro for InterlockedIncrement and InterlockedDecrement
didn't affect the parameter, rather it only returned the correct
result. This caused some subtle memory leaks, that, when fixed,
caused segfaults because an IMalloc structure was being used after
it had been freed because a refcount increment was missing during
CoGetMalloc, which allocates a brand new malloc and assigns it to
the given parameter, which creates a new reference.
Specifically, in the run I was debugging, DxcCreateBlobFromFile
created a null CComPtr, which it almost immediately assigned IMalloc
to, but since CoGetMalloc didn't increment the refcount, when the
function ended, the CComPtrBase destructor decremented the count
on the IMalloc without a corresponding increment when it was associated
with the …

[linux-port] fix refcounting on imalloc and others

---

include/dxc/Support/microcom.h
include/llvm/Support/WinMacros.h
lib/DxcSupport/FileIOHelper.cpp
tools/clang/tools/dxr/CMakeLists.txt
tools/clang/unittests/HLSL/CompilationResult.h
tools/clang/unittests/HLSL/HlslTestUtils.h
tools/clang/unittests/HLSLHost/CMakeLists.txt

InterlockedIncrement and InterlockedDecrement are atomic operations to
increment or decrement the value pointed to by the pointer parameter and
return the same. Currently they are implemented as simple addition
operations in WinMacros.h for non-win32 platforms which works well
enough, but wasn't really the original intent.
There are already platform abstractions available to LLVM in Atomics.h.
This change leverages them to implement the same functionality in a
platform-agnostic way. Mostly it's just a matter of swapping
InterlockedIncrement for AtomicIncrement.
Fixes half of https://github.com/google/DirectXShaderCompiler/issues/198

[linux-port] Thread-safe increment/decrement

---

lib/HLSL/DxilDebugInstrumentation.cpp
lib/HLSL/DxilGenerationPass.cpp
lib/HLSL/DxilRootSignature.cpp
lib/HLSL/DxilValidation.cpp
lib/HLSL/HLMatrixLowerPass.cpp
lib/HLSL/HLModule.cpp
lib/HLSL/HLOperationLower.cpp
lib/HLSL/HLSignatureLower.cpp
lib/IR/LegacyPassManager.cpp
lib/IR/Verifier.cpp
lib/Support/CommandLine.cpp
lib/Support/Timer.cpp
lib/Transforms/IPO/MergeFunctions.cpp
lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
tools/clang/lib/AST/ASTContextHLSL.cpp
tools/clang/lib/AST/ExprConstant.cpp
tools/clang/lib/AST/HlslTypes.cpp
tools/clang/lib/CodeGen/CGExprAgg.cpp
tools/clang/lib/CodeGen/CGExprCXX.cpp
tools/clang/lib/CodeGen/CGHLSLMS.cpp
tools/clang/lib/Parse/HLSLRootSignature.cpp
tools/clang/lib/Parse/ParseDecl.cpp
tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/TypeTranslator.cpp
tools/clang/lib/Sema/SemaExprObjC.cpp
tools/clang/lib/Sema/SemaHLSL.cpp
tools/clang/lib/Sema/SemaOpenMP.cpp
tools/clang/tools/dxcompiler/dxcdisassembler.cpp

Removes unused variables and functions from code between HLSL
change comments in LLVM code or else in HLSL or SPIRV original
source files along with any code correspondingly rendered unused
or originally in service of these ultimately unused elements.
Each of these produces a warning in clang, gcc, or both.
Fixes around 458 clang warnings and 461 gcc warnings.

[linux-port] Remove unused from HLSL code

---

include/dxc/HLSL/DxilSignatureAllocator.h
lib/HLSL/DxilContainerAssembler.cpp
lib/HLSL/HLMatrixLowerPass.cpp
tools/clang/lib/Sema/SemaHLSL.cpp

There is the possibility of a few variables being used without
initialization, which causes some warnings.
Fixes 2 clang warnings
GCC worries that assigning a variable to the result of an
assignment of that same variable may be undefined. It's a silly
thing to do anyway. So it's removed.
Fixes 1 gcc warning.
GCC is quite sure that Interp is too small to hold values of up
to 9 with only 4 bits. Perhaps because the RHS is a variable of
8 bits.
Fixes 47 gcc warnings

[linux-port] Scalar initialization warnings

---

include/dxc/HLSL/DxilMetadataHelper.h
include/dxc/HLSL/DxilModule.h
include/dxc/HLSL/DxilOperations.h
include/dxc/HLSL/DxilResourceBase.h
include/dxc/HLSL/DxilTypeSystem.h
include/dxc/HLSL/HLModule.h
lib/HLSL/DxilShaderAccessTracking.cpp
lib/HLSL/HLOperationLowerExtension.cpp
tools/clang/lib/SPIRV/GlPerVertex.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/Sema/SemaHLSL.cpp

Terminating classes may create a muscle memory for typing a
semicolon after a left-justified closed brace. Whatever the reason
to GCC's chagrine there were many functions ended with unnecessary
semicolons. Each one caused a warning. This removes them.
Fixes 285 GCC warnings

[linux-port] Remove extra semicolons

---

lib/HLSL/ComputeViewIdState.cpp
lib/HLSL/DxilOperations.cpp
lib/HLSL/DxilTypeSystem.cpp

Found as part of a project to eliminate warnings, but this is an
actual bug. An HLSL change adds the possibility of a Dxil and an
HLSL module to the base LLVM Module as well as the ability to
retrieve a reference to them when the are present. This reference
retrieval was mistakenly used to determine if the module was
present in spite of the fact that references are never null. Worse
the reference is from a dereferenced pointer, so if it wasn't there,
it would cause a null dereference. The module interface had methods
to query the presence of these submodules, but they weren't used.
fixes 4 clang warnings and possibly some mysterious crashes
The same warning for a different cause is encountered where an
address is taken of a value passed by reference and compared to
null, which can never …

[linux-port] Replace tests of never null addresses

---

include/dxc/Support/dxcapi.impl.h
include/dxc/Support/microcom.h
lib/DxcSupport/FileIOHelper.cpp
lib/HLSL/DxcOptimizer.cpp
tools/clang/lib/CodeGen/CGHLSLMS.cpp
tools/clang/tools/dxc/dxc.cpp
tools/clang/tools/dxcompiler/dxcassembler.cpp
tools/clang/tools/dxcompiler/dxclibrary.cpp
tools/clang/tools/dxcompiler/dxcompilerobj.cpp
tools/clang/tools/dxcompiler/dxcontainerbuilder.cpp
tools/clang/tools/dxcompiler/dxcvalidator.cpp
tools/clang/tools/libclang/dxcrewriteunused.cpp

Clang produces a warning when a method that overrides another is
not marked with the override keyword. Adding the keyword has no
effect on overridden functions, but it is good practice to mark
all methods intended to override as such because if they fail to
do so, the keyword will produce an error.
Fixes 78 Clang warnings.

[linux-port] Mark all overridden methods

---

include/dxc/Support/Global.h
lib/HLSL/DxilGenerationPass.cpp
lib/HLSL/DxilSignatureElement.cpp
lib/HLSL/HLMatrixLowerPass.cpp
lib/HLSL/HLModule.cpp
lib/HLSL/HLOperationLower.cpp
lib/HLSL/HLSignatureLower.cpp
lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
tools/clang/lib/CodeGen/CGHLSLMS.cpp
tools/clang/unittests/HLSL/ExecutionTest.cpp
tools/clang/unittests/HLSL/ShaderOpTest.cpp

The various DXASSERT macros produced a number of different warnings.
The most obvious was providing an empty string for a macro expecting
a message. Substituting in the _NOMSG macro fixes this.
Fixes 13 clang warnings.
A trickier problem for GCC and Clang is a variadic macro that is
provided no variadic arguments. Both Clang and GCC will avoid
errors by using the ##__VA_ARGS__ non-standard behavior, but it's
not an ideal solution. It turns out there aren't that many DXASSERT
macros that actually take variadic arguments. So I added an _ARGS
variant and replaced those instances with that. An ancillary benefit
is that non variadic asserts can present a message with the assert.
Fixes 583 clang warnings and 582 gcc warnings.
In what I expect was an earlier attempt to overload the DXASSERT …

[linux-port] Fix DXASSERT warnings

---

lib/HLSL/HLOperations.cpp
tools/clang/lib/CodeGen/CGClass.cpp
tools/clang/lib/Frontend/FrontendAction.cpp
tools/clang/lib/Sema/SemaChecking.cpp
tools/clang/tools/dxcompiler/dxcfilesystem.cpp
tools/clang/tools/dxcompiler/dxcutil.cpp

Remove pragma once from source files. It has no meaning in a source
file unless it's used as a header, which, fortunately, none of
these are.
Fixes 3 clang and 3 gcc warnings.
Remove trailing tokens after #endifs. Common result from copy,
paste, and slightly alter the beginning #if line to keep the
comments after consistent.
Fixes 3 clang and 3 gcc warnings.

[linux-port] Fix preprocessor warnings

---

include/dxc/HLSL/DxilPipelineStateValidation.h
lib/DxcSupport/FileIOHelper.cpp
lib/HLSL/DxilMetadataHelper.cpp
lib/HLSL/DxilRootSignature.cpp
tools/clang/tools/dxc/dxc.cpp
tools/clang/tools/dxcompiler/dxcdisassembler.cpp
tools/clang/tools/dxcompiler/dxcfilesystem.cpp

There are a lot of cases where const is carelessly cast off. Some
of them lead to really dramatic changes in multiple interfaces to
fix properly. This is instead a subset of cases where const was
disrespected, often for no apparent reason at all. likely just a
mistake in type casting.
Fixes 88 gcc and 88 clang warnings.

[linux-port] Correct const casts

---

include/llvm/Support/WinMacros.h
include/llvm/Support/WinTypes.h
lib/HLSL/ComputeViewIdState.cpp
lib/HLSL/DxilGenerationPass.cpp
lib/HLSL/DxilOperations.cpp
lib/HLSL/DxilValidation.cpp
lib/HLSL/HLSignatureLower.cpp
tools/clang/include/clang/Frontend/CompilerInstance.h
tools/clang/lib/AST/Decl.cpp
tools/clang/lib/Sema/SemaChecking.cpp
tools/clang/lib/Sema/SemaDeclObjC.cpp
tools/clang/lib/Sema/SemaHLSL.cpp

Simply including a variable as the entirity of an expression is
insufficient to silence warnings for gcc and clang. The variable
is not reported as unused, which is the intent, but the expression
result is reported in a warning as unused. By casting that
expression as (void), both warnings are silenced.
Fixes 110 clang and 40 gcc warnings.

[linux-port] Dummy access to unused variables

---

lib/DxcSupport/dxcapi.use.cpp
lib/HLSL/DxilOperations.cpp
lib/HLSL/DxilValidation.cpp
lib/HLSL/HLModule.cpp
lib/Transforms/IPO/PassManagerBuilder.cpp
lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
tools/clang/lib/AST/DeclPrinter.cpp
tools/clang/lib/CodeGen/CGCall.cpp
tools/clang/lib/CodeGen/CodeGenModule.cpp
tools/clang/lib/Lex/LiteralSupport.cpp
tools/clang/lib/Lex/TokenLexer.cpp
tools/clang/lib/Parse/ParseExpr.cpp
tools/clang/lib/Parse/ParseTemplate.cpp
tools/clang/lib/Parse/Parser.cpp
tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/TypeTranslator.cpp
tools/clang/lib/Sema/SemaHLSL.cpp
tools/clang/lib/Sema/SemaOverload.cpp

Clang and gcc complain when AND and OR logical operations are both
used in a single conditional because of the possibility of mistakes
when depending solely on operator precedence. In fact, this change
fixes a few clear errors mostly in asserts that would never fire.
Fixes 13 clang and 22 gcc warnings.
Additionally, when two if statements are followed by an else, there
may be some ambiguity in terms of which if the else applies to. It
is the closest one, the second in the case of two, but it is another
area of potential mistakes. Adding braces around the code intended
as the block of the first if conditional clarifies this.
fixed 8 clang and 8 gcc warnings.
Clang complains sometimes when assignments take place in a
conditional without additional parenthesis around it. It can
indicate when …

[linux-port] Correct conditional groupings

---

include/dxc/Support/WinIncludes.h
include/llvm/Support/WinTypes.h
lib/DxcSupport/FileIOHelper.cpp
tools/clang/tools/dxcompiler/dxcfilesystem.cpp
tools/clang/tools/dxr/dxr.cpp

A most pervasive warning from a minimal amount of code. The Wintypes
header included an anonymous struct in the form of LARGE_INTEGER
which is specified by Microsoft, but the actual MS header includes
another struct in the union for environments that don't want
anonymous structs. Given the minimal usage, I think this can
qualify. Microsoft's own headers will exclude the anonymous struct
in favor of the named one if NONAMELESSSTRUCT is defined before
windows.h. To prevent future uses of the anonymous part of LARGE_
INTEGER, this defines that in WinIncludes.h.
Fixes 148 clang and 148 gcc warnings.

[linux-port] Fix anonymous struct warnings

---

include/llvm/Support/WinFunctions.h
include/llvm/Support/WinTypes.h
lib/DxcSupport/dxcmem.cpp
lib/Support/CMakeLists.txt
lib/Support/WinFunctions.cpp
tools/clang/tools/dxc/dxc.cpp

Having fully implemented functions in a header file means that
every source file that includes it will get its own set of these
functions whether it uses them or not. If they are unused, they
are reported in an error as a defined but unused function. In a
common header, this happens a lot. By leaving only prototypes in
the header and putting the bodies in a source file, they are all
silenced.
Fixes 363 clang and 363 gcc warnings

[linux-port] Fix static function header warnings

---

include/dxc/HLSL/DxilRootSignature.h

pParameters and pStaticSamplers were both marked const in spite of
the qualifier being cast off at nearly every usage. So they lose
their const. If you're the target of memcpy or memset, you are
not const.
Fixes 12 gcc and 12 clang warnings

[linux-port] de-const variables not used as const

---

lib/HLSL/DxilGenerationPass.cpp
tools/clang/lib/Parse/HLSLRootSignature.cpp
tools/clang/lib/Parse/HLSLRootSignature.h
tools/clang/lib/SPIRV/DeclResultIdMapper.h
tools/clang/lib/SPIRV/GlPerVertex.cpp
tools/clang/lib/SPIRV/GlPerVertex.h
tools/clang/tools/dxcompiler/dxcompilerobj.cpp

Clang is smart enough to detect when a class member function or
variable is not used and emits a warning for that case. This
removes all such members as well as any corresponding parameters
and other variables that might have been used to initialize such.
Fixes 8 clang warnings.

[linux-port] Remove unused class components

---

external/CMakeLists.txt
external/GTestConfig.cmake
tools/clang/unittests/SPIRV/DecorationTest.cpp
tools/clang/unittests/SPIRV/ModuleBuilderTest.cpp

clang-spirv-tests uses a lot of external projects that keep
themselves clean with different standards of warnings flags.
This alters the appropriate cmake files to disable flags that
the DXC build enables.
Fixes 72 gcc and 166 clang warnings.
Additionally catch some sign mismatch comparisons in tests
built as part of clang-spirv-tests.
Fixes 2 gcc and 2 clang warnings, but one of them has multiple sources
So it's kind of a lot more.

[linux-port] Fix spirv test warnings

---

include/llvm/Support/WinMacros.h
tools/clang/tools/dxcompiler/dxillib.cpp

InitializeCriticalSection, DeleteCriticalSection, EnterCriticalSection,
and LeaveCriticalSection serve to create a mutual exclusion section of
code, but they are stubbed out currently for non-win platforms.
There is multi-platform support for the same functionality in LLVM
in the form of SmartMutex. This switches from the Windows specific
to the abstraction, allowing the same code to work on other platforms.
Fixes half of https://github.com/google/DirectXShaderCompiler/issues/198

[linux-port] Cross-platform critical section

---

include/llvm/Support/WinMacros.h
lib/DxcSupport/FileIOHelper.cpp
lib/DxcSupport/dxcapi.use.cpp

errno is guaranteed to be a positive number. The existing
conversions to/from hresult to error codes work well.
I am able to see the appropriate error messages being passed to the
user. For example, if I specify an input file that doesn't exist (test.hlsl), I get
the following error on Linux:
`No such file or directory ~/hlsl/test.hlsl`

[linux-port] Use errno instead of Win error codes.

---

include/dxc/Support/ErrorCodes.h

The errno as GetLastError change exposed previously excluded
but existing code to *nix compilers that contains a unsigned/
signed comparison that produces a warning. Simple fix for a
simple warning.

[linux-port] fix simple ErrorCodes.h warning

---

include/dxc/Support/WinAdapter.h
include/llvm/Support/WinFunctions.h
lib/DxcSupport/FileIOHelper.cpp
lib/DxcSupport/WinAdapter.cpp
lib/DxcSupport/dxcapi.use.cpp
lib/Support/WinFunctions.cpp
tools/clang/tools/dxc/dxc.cpp

Add CreateFile*, Read/WriteFile, and other Windows interfaces for
file management. Also add CHandle for scope-based file closure.
This allows more shared code, implicitly implements some
features missing from the Unix implementation, and prevents
inconsistencies in when files are closed. i.e. WriteHeader in dxc.cpp
called WriteString twice on the same file, though WriteString closed
that file.

[linux-port] Implement Win file IO funcs for *nix

---

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp

A persistent and occasionally confusing warning is produced on
Windows release builds because of a conditional expression that only
contains an assert. On a release build, this amounts to nothing but
a semicolon, which produces the warning.
This folds the conditional into the previously explicit assert so
it is included or excluded entirely regardless of build type.

Fix warning on windows release builds

---

tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.cpp

ModuleBuilder had a catch-all function to apply decorations not
taking additional parameters, however, every single call to this
has an explicit decoration parameter. The switch only slows things
down and doesn't help with code length or anything else. The switch
is missing the other decorations that have custom functions, which
produce warnings. Rather than add a default: case, I've provided
custom decorate functions for each decoration.
Helps https://github.com/google/DirectXShaderCompiler/issues/206

[linux-port] Multiplex ModuleBuilder decorations

---

.travis.yml

When the clang compiler is used, there is no need to install gcc5.
By adding gcc as special case, addons and environment variables can
be set custom just for these exceptional cases while expediting the
clang builds by skipping this unnecessary installation.

[linux-port] avoid unnecessary gcc5 installation

---

include/dxc/Support/Global.h
lib/HLSL/ComputeViewIdState.cpp
lib/HLSL/DxilDebugInstrumentation.cpp
lib/HLSL/DxilGenerationPass.cpp
lib/HLSL/HLMatrixLowerPass.cpp
lib/HLSL/HLOperationLower.cpp
lib/HLSL/HLSignatureLower.cpp
lib/Transforms/Scalar/IndVarSimplify.cpp
lib/Transforms/Scalar/PlaceSafepoints.cpp
lib/Transforms/Scalar/SROA.cpp
lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
tools/clang/lib/CodeGen/CGCall.cpp
tools/clang/lib/CodeGen/CGHLSLMS.cpp
tools/clang/lib/Frontend/FrontendActions.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/TypeTranslator.cpp
tools/clang/lib/Sema/SemaDecl.cpp

A number of warnings unique to release builds persist. Some of these
same errors were fixed earlier for debug builds, but are different for
release that excludes some of the usage and other code.
DXASSERT_LOCALVAR still took a variadic macro on release builds.
Fixes 85 clang warnings
Expressions used only as conditionals for asserts were not properly
dummied out with (void) cast.
Fixes 7 clang warnings
Variables used only in asserts dummied out.
Fixes 27 clang warnings
Potential uninitilized uses of variables assigned in switches/ifs.
fixes 5 clang warnings
put braces around empty else statements
11 gcc warnings
Helps https://github.com/google/DirectXShaderCompiler/issues/206

[linux-port] Eliminate warnings on release builds

---

.travis.yml
include/dxc/Support/Global.h
include/dxc/Support/dxcapi.use.h
lib/DxcSupport/HLSLOptions.cpp
lib/DxcSupport/dxcmem.cpp
lib/Support/regerror.c
lib/Support/regex_impl.h
tools/clang/tools/dxcompiler/CMakeLists.txt
tools/clang/tools/dxcompiler/DXCompiler.cpp

MacOS resolves symbols differently from Linux. Linux takes the first
valid resolution and then uses it wherever it is referenced. MacOS
more similar to Windows, favors symbols that are local to the
compilation unit.
This comes into play where functions set static globals such as
the malloc tls and the IMalloc contained there. The dxc binary
initializes these. For Linux, that's enough because all calls
resolve to the ones from this binary because they are encountered
first. MacOS calls that originate from within the dynamic library
resolve to the local functions, which don't have their globals
initialized. To initialize them, we need to do what is done in
DLLMain in DXCompiler.cpp.
Performing these calls results in duplicate initializations on Linux
unless the calls in question are given …

[macos-port] Allow dxc and tests to run on mac

---

.travis.yml
appveyor.yml
tools/CMakeLists.txt
tools/clang/tools/CMakeLists.txt
tools/clang/unittests/CMakeLists.txt

After this change, you can simply run 'ninja', and you'll get the 'dxc'
target and 'clang-spirv-tests' target built.

[linux-port] Disable win-only targets on other platforms.

---

include/dxc/Support/WinAdapter.h
lib/DxcSupport/WinAdapter.cpp

We should use the Allocator's methods rather than directly using
malloc/free/etc.
Also fixed a bug: shouldn't access m_count after it has been potentially
deleted.

[linux-port] Fix a couple of adapter issues.

---

include/llvm/Analysis/TargetLibraryInfo.def
lib/Analysis/TargetLibraryInfo.cpp
lib/Transforms/IPO/FunctionAttrs.cpp

Alpine Linux and probably several others, define fopen64, fseeko64,
ftello64, and tmpfile64 to their 32 bit equivalents in system
headers. This results in duplicates in areas of the code that
include 32 bit and 64 bit references to this. Since HLSL doesn't
have any of these functions anyway, we can safely remove them.
Fixes https://github.com/google/DirectXShaderCompiler/issues/253

[linux-port] Fix gcc6.4 alpine(and others) compile

---

include/dxc/Support/WinAdapter.h
include/dxc/Support/dxcapi.use.h
lib/Support/CMakeLists.txt
tools/clang/tools/dxcompiler/dxillib.cpp

LLVM includes a DynamicLibrary class that works on multiple platforms
Rather than ifdefing between dlopen for non-Windows and LoadLibraryW
on Windows, using this class allows us to abstract platform differences
while using the same code.
Changed DxilLibInitialize to attempt to initialize dxil.dll so the
smart mutex inside the dynamic library object uses the same IMalloc
as the other ManagedStatic objects so they can all be freed in order.

[linux-port] Use cross-platform dynamic lib load

---

include/llvm/Analysis/TargetLibraryInfo.def
lib/Analysis/TargetLibraryInfo.cpp
lib/Transforms/IPO/FunctionAttrs.cpp

To be consistent with other changes to LLVM code, we should if 0
or comment out the problem portions with compiling on Alpine Linux
and others. The previous commit removed them entirely.
Fixes https://github.com/google/DirectXShaderCompiler/issues/253

[linux-port] exclude problem code with if 0

---

tools/clang/include/clang/SPIRV/SPIRVContext.h
tools/clang/include/clang/SPIRV/SpirvType.h
tools/clang/include/clang/SPIRV/SpirvVisitor.h
tools/clang/lib/SPIRV/CMakeLists.txt
tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
tools/clang/lib/SPIRV/LowerTypeVisitor.h
tools/clang/lib/SPIRV/SPIRVContext.cpp
tools/clang/lib/SPIRV/SpirvType.cpp

This visitor will be used in the new CodeGen infra for lowering
Clang AST QualType into SPIR-V types.
The logic for layout decorations is removed from this visitor;
we will have a separate class for layout decorations.

[spirv] LowerTypeVisitor: AST type into SPIR-V type

---

tools/clang/include/clang/SPIRV/SPIRVContext.h
tools/clang/include/clang/SPIRV/SpirvInstruction.h
tools/clang/include/clang/SPIRV/SpirvModule.h
tools/clang/lib/SPIRV/EmitVisitor.cpp
tools/clang/lib/SPIRV/SPIRVContext.cpp
tools/clang/lib/SPIRV/SpirvInstruction.cpp
tools/clang/lib/SPIRV/SpirvModule.cpp
tools/clang/lib/SPIRV/SpirvType.cpp
tools/clang/unittests/SPIRV/SpirvConstantTest.cpp

The main motivation of this change is to eliminate usage of ASTContext and QualType when asking for SPIR-V constants.

[spirv] Improve SpirvConstant class APIs.

---

tools/clang/include/clang/SPIRV/EmitVisitor.h
tools/clang/include/clang/SPIRV/SPIRVContext.h
tools/clang/include/clang/SPIRV/SpirvType.h
tools/clang/lib/SPIRV/EmitVisitor.cpp
tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
tools/clang/lib/SPIRV/SPIRVContext.cpp
tools/clang/lib/SPIRV/SpirvType.cpp

Pulls decoration logic out of TypeTranslator and declResultIdMapper and puts it all in one place.

[spirv] Emit decorations for types.

---

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp

This change tries to make this function less messy and uses QualType
rather than integer type-id as much as possible. This will help with
switching to the new infrastructure.

[spirv] Cleanup the createStageVars function.

---

tools/clang/include/clang/SPIRV/SpirvInstruction.h
tools/clang/lib/SPIRV/SpirvInstruction.cpp
tools/clang/unittests/SPIRV/SpirvConstantTest.cpp

Supporting spec constants is needed for switching to the new infrastructure.

[spirv] Handle Spec constants in SpirvConstant class
