google/DirectXShaderCompiler

tools/clang/include/clang/SPIRV/Decoration.h
tools/clang/lib/SPIRV/Decoration.cpp
tools/clang/unittests/SPIRV/DecorationTest.cpp

- Added a unit test for every kind of decoration
- A couple of bug fixes

Add Decoration Unit Tests

---

tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/include/clang/SPIRV/Structure.h
tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/lib/SPIRV/Structure.cpp
tools/clang/test/CodeGenSPIRV/empty-void-main.hlsl2spv
tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv
tools/clang/test/CodeGenSPIRV/passthru-vs.hlsl2spv
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

The code currently doesn't handle input/output interfaces.
The test files have been updated to reflect these changes.

[spirv] CodeGen for OpEntryPoint

---

tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/include/clang/SPIRV/Structure.h
tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv
tools/clang/test/CodeGenSPIRV/passthru-vs.hlsl2spv

[spirv] CodeGen for OpFunctionParameter

---

tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/include/clang/SPIRV/Structure.h
tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/lib/SPIRV/Structure.cpp
tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv
tools/clang/test/CodeGenSPIRV/passthru-vs.hlsl2spv
tools/clang/unittests/SPIRV/ModuleBuilderTest.cpp

* Add support for generating stage IO variables
* Add support for interface variable ids in entry point
* Add support for OpReturnValue

[spirv] Fully translate pass-through pixel shader!

---

tools/clang/include/clang/SPIRV/InstBuilder.h
tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/include/clang/SPIRV/Structure.h
tools/clang/include/clang/SPIRV/Type.h
tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/lib/SPIRV/InstBuilderManual.cpp
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/lib/SPIRV/Structure.cpp
tools/clang/lib/SPIRV/Type.cpp
tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv
tools/clang/test/CodeGenSPIRV/passthru-vs.hlsl2spv
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
tools/clang/unittests/SPIRV/StructureTest.cpp
tools/clang/unittests/SPIRV/WholeFileCheck.cpp

* Handled structs as entry point output type
* Handled local variable of struct type
* Replaced the term of "interface variable" with "stage variable"

[spirv] Fully translate pass-through vertex shader!

---

tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/include/clang/SPIRV/Structure.h
tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/lib/SPIRV/Structure.cpp
tools/clang/test/CodeGenSPIRV/constant.scalar.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

Also add support for constant variable initializers.

[spirv] Constants for primitive types: bool, int/uint, float

---

tools/clang/include/clang/SPIRV/InstBuilder.h
tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/lib/SPIRV/InstBuilderManual.cpp
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/test/CodeGenSPIRV/binary-op.arithmetic.scalar.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

* Covers the following operations: +, -, *, /, %

[spirv] Translate arithmetic operations for integers and floats

---

tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/test/CodeGenSPIRV/if-stmt.nested.hlsl
tools/clang/test/CodeGenSPIRV/if-stmt.plain.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

Support plain and nested if statments now. Complicated cases (like
with early returns and other control flow statements in body) yet
to be covered.
Note that the order of generated basic blocks are slightly off; I'll
have an additional PR after the `for` loop support for fix them.

[spirv] Translate if statement

---

tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/test/CodeGenSPIRV/binary-op.comparison.scalar.hlsl
tools/clang/test/CodeGenSPIRV/for-stmt.plain.hlsl
tools/clang/test/CodeGenSPIRV/unary-op.prefix-inc.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

* Only the basic for statement are tested. More complicated cases
yet to be implemented and tested.
* Also add support for less than and prefix increment operator.

[spirv] Translate for statement

---

tools/clang/include/clang/SPIRV/InstBuilder.h
tools/clang/include/clang/SPIRV/Structure.h
tools/clang/lib/SPIRV/InstBuilderAuto.cpp
tools/clang/lib/SPIRV/Structure.cpp
tools/clang/unittests/SPIRV/CMakeLists.txt
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
tools/clang/unittests/SPIRV/InstBuilderTest.cpp
tools/clang/unittests/SPIRV/ModuleBuilderTest.cpp
tools/clang/unittests/SPIRV/SPIRVContextTest.cpp
tools/clang/unittests/SPIRV/SPIRVTestUtils.h
tools/clang/unittests/SPIRV/StructureTest.cpp
tools/clang/unittests/SPIRV/TestMain.cpp
tools/clang/unittests/SPIRV/WholeFileTestFixture.cpp
tools/clang/unittests/SPIRV/WholeFileTestFixture.h

* Changed Instruction to a class
* Created SimpleInstBuilder for building instructions in tests
* Various cosmetic changes

[spirv] Improve SPIR-V structures and tests for them

---

tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/test/CodeGenSPIRV/binary-op.arithmetic.mixed.hlsl
tools/clang/test/CodeGenSPIRV/binary-op.arithmetic.vector.hlsl
tools/clang/test/CodeGenSPIRV/binary-op.comparison.mixed.hlsl
tools/clang/test/CodeGenSPIRV/binary-op.comparison.vector.hlsl
tools/clang/test/CodeGenSPIRV/constant.vector.hlsl
tools/clang/test/CodeGenSPIRV/type.vector.hlsl
tools/clang/test/CodeGenSPIRV/unary-op.prefix-inc.hlsl
tools/clang/test/CodeGenSPIRV/var.init.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

* Translated vector types and operations on vector types
* +, -, *, /, % on vector <op> vector and vector <op> scalar
* Prefix increment on vectors
* < on vector <op> vector and vector <op> scalar
* Covered both constant initializer and variable initializer
* Applied constant modifier to variables

[spirv] Translate vector types and handle variable initializers

---

docs/SPIR-V.rst
tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/test/CodeGenSPIRV/binary-op.comparison.scalar.hlsl
tools/clang/test/CodeGenSPIRV/binary-op.comparison.vector.hlsl

* Covers <, <=, >, >=, ==, !=
* For both scalars and vectors
* Also update docs about arithmetic and comparison operators

[spirv] Translate all comparision operators

---

tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/test/CodeGenSPIRV/binary-op.arith-assign.mixed.hlsl
tools/clang/test/CodeGenSPIRV/binary-op.arith-assign.scalar.hlsl
tools/clang/test/CodeGenSPIRV/binary-op.arith-assign.vector.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

[spirv] Translate arithmetic assign operators

---

docs/SPIR-V.rst
tools/clang/include/clang/SPIRV/InstBuilder.h
tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/lib/SPIRV/InstBuilderManual.cpp
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/test/CodeGenSPIRV/binary-op.bitwise-assign.mixed.hlsl
tools/clang/test/CodeGenSPIRV/binary-op.bitwise-assign.scalar.hlsl
tools/clang/test/CodeGenSPIRV/binary-op.bitwise-assign.vector.hlsl
tools/clang/test/CodeGenSPIRV/binary-op.bitwise.mixed.hlsl
tools/clang/test/CodeGenSPIRV/binary-op.bitwise.scalar.hlsl
tools/clang/test/CodeGenSPIRV/binary-op.bitwise.vector.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

* Covers ~, &, |, ^, <<, >>, &=, |=, ^=, <<=, >>=
* For int/uint and vector of int/uint

[spirv] Translate bitwise operators

---

tools/clang/lib/AST/ExprConstant.cpp
tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/test/CodeGenSPIRV/cast.2bool.explicit.hlsl
tools/clang/test/CodeGenSPIRV/cast.2bool.implicit.hlsl
tools/clang/test/CodeGenSPIRV/cast.no-op.hlsl
tools/clang/test/CodeGenSPIRV/var.init.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

* Supported converting scalar/vector sint/uint/float values into
scalar/vector bool values.

[spirv] Translate casting to bool (vector) values

---

docs/SPIR-V.rst
tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/test/CodeGenSPIRV/cast.vector.splat.hlsl
tools/clang/test/CodeGenSPIRV/cast.vector.trunc.hlsl
tools/clang/test/CodeGenSPIRV/type.vector.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

* Also added tests for vector<|type|, |count|> format.

[spirv] Translate vector truncation and splatting

---

tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/test/CodeGenSPIRV/intrinsics.all.hlsl
tools/clang/test/CodeGenSPIRV/intrinsics.any.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

The current implementation doesn't take matrix type as parameter yet.

[spirv] Translate intrinsic 'all' and 'any'.

---

tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/test/CodeGenSPIRV/intrinsics.asfloat.hlsl
tools/clang/test/CodeGenSPIRV/intrinsics.asint.hlsl
tools/clang/test/CodeGenSPIRV/intrinsics.asuint.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

The current implementation does not support matrix arguments.

[spirv] Translate intrinsic asfloat, asint, asuint

---

docs/SPIR-V.rst
tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.h
tools/clang/test/CodeGenSPIRV/for-stmt.nested.hlsl
tools/clang/test/CodeGenSPIRV/while-stmt.nested.hlsl
tools/clang/test/CodeGenSPIRV/while-stmt.plain.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

Also added the translation for `loop` and `unroll` attributes.
Similar to for loops, the current implementation does not support early
exits, or early returns.

[spirv] Translation of while loops.

---

tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.h
tools/clang/test/CodeGenSPIRV/if-stmt.plain.hlsl

Also use BinaryOperator methods to test compound assignment.

[spirv] Handle variable definitions in if statements

---

tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.h
tools/clang/lib/SPIRV/TypeTranslator.cpp
tools/clang/lib/SPIRV/TypeTranslator.h
tools/clang/test/CodeGenSPIRV/binary-op.arith-assign.mixed.hlsl
tools/clang/test/CodeGenSPIRV/binary-op.arithmetic.mixed.hlsl

SPIR-V has a specific OpMatrixTimesScalar for scaling FP matrices.

[spirv] Optimize FP matrix and scalar multiplication codegen

---

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
tools/clang/lib/SPIRV/DeclResultIdMapper.h
tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.h

Previously we parse the string by ourselves.

[spirv] Create hlsl::ShaderModel out of shader model string

---

tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.h
tools/clang/lib/SPIRV/TypeTranslator.cpp
tools/clang/lib/SPIRV/TypeTranslator.h
tools/clang/test/CodeGenSPIRV/intrinsics.all.hlsl
tools/clang/test/CodeGenSPIRV/intrinsics.any.hlsl
tools/clang/test/CodeGenSPIRV/intrinsics.asfloat.hlsl

Addressed comments and fixed the return type bug.

[spirv] Matrix for any,all,asfloat,asint,asuint.

---

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
tools/clang/lib/SPIRV/DeclResultIdMapper.h
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv
tools/clang/test/CodeGenSPIRV/passthru-vs.hlsl2spv
tools/clang/test/CodeGenSPIRV/semantic.arbitrary.hlsl
tools/clang/test/CodeGenSPIRV/semantic.depth.ps.hlsl
tools/clang/test/CodeGenSPIRV/semantic.instance-id.ps.hlsl
tools/clang/test/CodeGenSPIRV/semantic.instance-id.vs.hlsl
tools/clang/test/CodeGenSPIRV/semantic.position.ps.hlsl
tools/clang/test/CodeGenSPIRV/semantic.position.vs.hlsl
tools/clang/test/CodeGenSPIRV/semantic.target.ps.hlsl
tools/clang/test/CodeGenSPIRV/semantic.vertex-id.vs.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

The location assignment is not handled yet. Nor does semantics within structs.

Support Position, Target, Depth, VertexID and InstanceID in VS and PS

---

docs/SPIR-V.rst
tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
tools/clang/lib/SPIRV/DeclResultIdMapper.h
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.h
tools/clang/test/CodeGenSPIRV/spirv.storage-class.hlsl
tools/clang/test/CodeGenSPIRV/var.static.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

These variables should be using the Private storage class.
And local static variables should be initialized once.

[spirv] Handle static global and local variables

---

tools/clang/lib/SPIRV/InitListHandler.cpp
tools/clang/lib/SPIRV/InitListHandler.h
tools/clang/test/CodeGenSPIRV/constant.matrix.hlsl
tools/clang/test/CodeGenSPIRV/constant.struct.hlsl
tools/clang/test/CodeGenSPIRV/type.struct.hlsl
tools/clang/test/CodeGenSPIRV/var.init.matrix.1x1.hlsl
tools/clang/test/CodeGenSPIRV/var.init.matrix.1xn.hlsl
tools/clang/test/CodeGenSPIRV/var.init.matrix.mx1.hlsl
tools/clang/test/CodeGenSPIRV/var.init.matrix.mxn.hlsl
tools/clang/test/CodeGenSPIRV/var.init.struct.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

Now we can decompose matrices appeared in init lists. Also we can
decompose and construct structs from init lists.

[spirv] More support for matrix and struct type in init lists

---

tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/TypeTranslator.cpp
tools/clang/test/CodeGenSPIRV/fn.call.hlsl
tools/clang/test/CodeGenSPIRV/fn.param.inout.hlsl
tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv
tools/clang/test/CodeGenSPIRV/passthru-vs.hlsl2spv
tools/clang/test/CodeGenSPIRV/spirv.entry-function.inout.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

We need to write out the values for parameters having out/inout
modifiers.

[spirv] Support input modifiers on function parameters

---

docs/SPIR-V.rst

* Explain how HLSL semantics are handled
* Restructure the doc

[spirv] Update SPIR-V.rst doc

---

tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/lib/SPIRV/InitListHandler.cpp
tools/clang/lib/SPIRV/InitListHandler.h
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.h
tools/clang/lib/SPIRV/TypeTranslator.cpp
tools/clang/test/CodeGenSPIRV/constant.array.hlsl
tools/clang/test/CodeGenSPIRV/op.array.access.hlsl
tools/clang/test/CodeGenSPIRV/type.array.hlsl
tools/clang/test/CodeGenSPIRV/var.init.array.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

* Supported constant array types
* Supported operator[] on arrays
* Supported initializer list containing arrays

[spirv] Add support for constant array type

---

tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.h
tools/clang/test/CodeGenSPIRV/intrinsics.clamp.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

Uses SPIR-V Extended Instructions for GLSL.

[spirv] Process clamp intrinsic function.

---

tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/include/clang/SPIRV/Structure.h
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.h
tools/clang/lib/SPIRV/Structure.cpp
tools/clang/test/CodeGenSPIRV/cf.if.for.hlsl
tools/clang/test/CodeGenSPIRV/constant-ps.hlsl2spv
tools/clang/test/CodeGenSPIRV/do-stmt.break.hlsl
tools/clang/test/CodeGenSPIRV/do-stmt.continue.hlsl
tools/clang/test/CodeGenSPIRV/do-stmt.nested.hlsl
tools/clang/test/CodeGenSPIRV/empty-void-main.hlsl2spv
tools/clang/test/CodeGenSPIRV/for-stmt.break.hlsl
tools/clang/test/CodeGenSPIRV/for-stmt.continue.hlsl
tools/clang/test/CodeGenSPIRV/for-stmt.nested.hlsl
tools/clang/test/CodeGenSPIRV/if-stmt.nested.hlsl
tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv
tools/clang/test/CodeGenSPIRV/passthru-vs.hlsl2spv
tools/clang/test/CodeGenSPIRV/switch-stmt.ifstmt.hlsl
tools/clang/test/CodeGenSPIRV/switch-stmt.opswitch.hlsl
tools/clang/test/CodeGenSPIRV/while-stmt.break.hlsl
tools/clang/test/CodeGenSPIRV/while-stmt.continue.hlsl
tools/clang/test/CodeGenSPIRV/while-stmt.nested.hlsl

This change removes a lot of the complexity of handling unreachable statements (statements after break, continue, discard, and early return).

[spirv] Better handling of unreachable statements.

---

tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
tools/clang/lib/SPIRV/DeclResultIdMapper.h
tools/clang/lib/SPIRV/ModuleBuilder.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/TypeTranslator.cpp
tools/clang/lib/SPIRV/TypeTranslator.h
tools/clang/test/CodeGenSPIRV/op.cbuffer.access.hlsl
tools/clang/test/CodeGenSPIRV/type.cbuffer.hlsl
tools/clang/test/CodeGenSPIRV/vk.binding.explicit.hlsl
tools/clang/test/CodeGenSPIRV/vk.binding.implicit.hlsl
tools/clang/test/CodeGenSPIRV/vk.binding.register.hlsl
tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.nested.std140.hlsl
tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.std140.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

* Added support for the cbuffer type
* Added support for accessing elements in cbuffer
* Added support for std140 layout rules

[spirv] Support cbuffer and layout decorations

---

tools/clang/lib/SPIRV/SPIRVEmitter.cpp
tools/clang/lib/SPIRV/SPIRVEmitter.h
tools/clang/test/CodeGenSPIRV/compute.byte-address-buffer.store.hlsl
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

These functions are defined for RWByteAddressBuffers.

[spirv] Translate Store, Store2, Store3, Store4.

---

tools/clang/test/CodeGenSPIRV/passthru-cs.hlsl2spv
tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp

Using raw buffers (ByteAddressBuffer and RWByteAddressBuffer).

[spirv] Add test for passthrough compute shader.

---

.travis.yml
appveyor.yml
lib/Support/CommandLine.cpp

It seems that there is an issue with command line processing, causing
the following failure:
LLVM ERROR: IO failure on output stream.
I'll file a case to address this hack.

[linux-port] Roll back PR #171.

---

lib/DxcSupport/LLVMBuild.txt
lib/HLSL/LLVMBuild.txt

Also add missing dependencies for lib/HLSL.
These dependencies only manifest themselves in Debug mode.

[linux-port] Define LLVMBuild.txt for DxcSupport.

---

CMakeLists.txt
cmake/modules/AddLLVM.cmake
cmake/modules/HandleLLVMOptions.cmake
tools/clang/lib/Sema/CMakeLists.txt
tools/clang/tools/dxc/CMakeLists.txt
tools/clang/tools/dxcompiler/CMakeLists.txt

Removing this kind of comment for changes that are not SPRIV-specific.

[linux-port] Remove "SPIRV Change Starts/Ends"

---

lib/DxcSupport/dxcmem.cpp

LLVM includes cross-platform thread local storage methods for
saving, retrieving, and deleting thread-specific objects. Using
these methods is superior to the thread_local storage qualifier
because the former works on Apple, Linux, and Windows. It also
uses the same mechanism as the previous Windows implementation
used without compiler idiosyncracies.
Placement new is needed in DxcInitThreadMalloc because operator
new requires the TLS malloc to be in place.
Fixes https://github.com/google/DirectXShaderCompiler/issues/173

[linux-port] Use cross-platform TLS methods

---

lib/Support/CommandLine.cpp
lib/Support/Debug.cpp

[linux-port] Use existing infra for debug messages.

---

docs/DxcOnUnix.rst

Add python to build requirements

---

include/dxc/Support/WinAdapter.h
tools/clang/tools/dxc/dxc.cpp

Tried to make changes less invasive.

[linux-port] Clean up dxc.cpp.

---

tools/clang/include/clang/SPIRV/SpirvInstruction.h
tools/clang/lib/SPIRV/SpirvBasicBlock.cpp
tools/clang/lib/SPIRV/SpirvInstruction.cpp

Also reordered and polished instruction classes

[spirv] Add LLVM-style RTTI to instruction classes

---

tools/clang/include/clang/SPIRV/EmitVisitor.h
tools/clang/include/clang/SPIRV/ModuleBuilder.h
tools/clang/include/clang/SPIRV/SpirvBuilder.h
tools/clang/include/clang/SPIRV/SpirvInstruction.h
tools/clang/include/clang/SPIRV/SpirvModule.h
tools/clang/include/clang/SPIRV/SpirvVisitor.h
tools/clang/lib/SPIRV/EmitVisitor.cpp
tools/clang/lib/SPIRV/SpirvBuilder.cpp
tools/clang/lib/SPIRV/SpirvInstruction.cpp
tools/clang/lib/SPIRV/SpirvModule.cpp

Also added EndPrimitive and EmitVertex instructions.

[spirv] Add module structure methods to SpirvBuilder.

---

tools/clang/include/clang/SPIRV/EmitVisitor.h
tools/clang/include/clang/SPIRV/SPIRVContext.h
tools/clang/include/clang/SPIRV/SpirvFunction.h
tools/clang/include/clang/SPIRV/SpirvInstruction.h
tools/clang/include/clang/SPIRV/SpirvModule.h
tools/clang/include/clang/SPIRV/SpirvType.h
tools/clang/include/clang/SPIRV/SpirvVisitor.h
tools/clang/lib/SPIRV/EmitVisitor.cpp
tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
tools/clang/lib/SPIRV/LowerTypeVisitor.h
tools/clang/lib/SPIRV/SPIRVContext.cpp
tools/clang/lib/SPIRV/SpirvFunction.cpp
tools/clang/lib/SPIRV/SpirvInstruction.cpp
tools/clang/lib/SPIRV/SpirvType.cpp

Currently doesn't emit any decorations. Will look into that next.

[spirv] Add EmitTypeHandler
